### ISSUE TITLE
Sign Compiler with Apple

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/roborio-toolchain#13]
<img width="532" alt="Screen Shot 2019-10-17 at 5 38 46 PM" src="https://user-images.githubusercontent.com/3799260/67057370-1589e580-f105-11e9-89c3-1a02987aab35.png">

We should sign the tools with apple to make the user experience more seamless: https://developer.apple.com/news/?id=09032019a

**Comment by AustinShalit** [comment]
https://bugs.launchpad.net/gcc-arm-embedded/+bug/1832620

**Comment by RyanHir** [comment]
https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/ of possible interest. It appears gon is not specific to golang and could possibly work here

**Comment by prateekma** [comment]
Thanks for the resource! I actually started to look into this issue about a week ago and this is certainly an option that I'll investigate.
