### ISSUE TITLE
Remove glibc/libgcc debug sources from distribution

### ISSUE THREAD

**Issue by PeterJohnson** [wpilibsuite/roborio-toolchain#28]
The glibc and libgcc source code is included in the distribution (in arm-frc2021-linux-gnueabi/usr/src/debug), accounting for about half of the total installed files.  This is likely a not insignificant contributor to installation time and these files are unlikely to be useful for debugging.

**Comment by RyanHir** [comment]
Removing the entirety of `arm-frc2021-linux-gnueabi/usr/src` did not affect compiling in any way. This was verfied by checking the binary hash after compiling. The following should work under Windows 10 to detect any binary difference.
```
# Baseline
.\bin\arm-frc2021-linux-gnueabi-gcc.exe .\main.c
Get-FileHash .\a.out

# Delete directory

# Run again to verify hash
.\bin\arm-frc2021-linux-gnueabi-gcc.exe .\main.c
Get-FileHash .\a.out
```

**Comment by PeterJohnson** [comment]
Fixed in 2022 branch.
